"""esquema inicial NexuStock

Revision ID: 5fde68443c14
Revises:
Create Date: 2026-08-12 20:31:31.747790

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5fde68443c14"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresa",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("identificacion_fiscal", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("telefono", sa.String(length=30), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=True),
        sa.Column("pais", sa.String(length=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("idioma", sa.String(length=10), nullable=False),
        sa.Column("zona_horaria", sa.String(length=64), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("motivo_suspension", sa.String(length=255), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "estado IN ('activa','suspendida','cancelada')", name="ck_empresa_estado"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("identificacion_fiscal"),
    )
    with op.batch_alter_table("empresa", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_empresa_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(batch_op.f("ix_empresa_estado"), ["estado"], unique=False)

    op.create_table(
        "limite_solicitud",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("clave_hash", sa.String(length=64), nullable=False),
        sa.Column("ruta", sa.String(length=120), nullable=False),
        sa.Column("ventana_inicio", sa.DateTime(), nullable=False),
        sa.Column("expira_en", sa.DateTime(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.CheckConstraint("cantidad >= 1", name="ck_limite_solicitud_cantidad"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "clave_hash", "ruta", "ventana_inicio", name="uq_limite_solicitud_ventana"
        ),
    )
    with op.batch_alter_table("limite_solicitud", schema=None) as batch_op:
        batch_op.create_index("ix_limite_solicitud_expira", ["expira_en"], unique=False)

    op.create_table(
        "plan_saas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("precio_mensual", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("precio_anual", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("dias_prueba", sa.Integer(), nullable=False),
        sa.Column("limite_productos", sa.Integer(), nullable=True),
        sa.Column("limite_usuarios", sa.Integer(), nullable=True),
        sa.Column("limite_movimientos_mes", sa.Integer(), nullable=True),
        sa.Column("limite_sucursales", sa.Integer(), nullable=True),
        sa.Column("limite_bodegas", sa.Integer(), nullable=True),
        sa.Column("almacenamiento_mb", sa.Integer(), nullable=True),
        sa.Column("funciones", sa.JSON(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("dias_prueba >= 0", name="ck_plan_dias_prueba"),
        sa.CheckConstraint(
            "limite_bodegas IS NULL OR limite_bodegas >= 0", name="ck_plan_limite_bodegas"
        ),
        sa.CheckConstraint(
            "limite_movimientos_mes IS NULL OR limite_movimientos_mes >= 0",
            name="ck_plan_limite_movimientos",
        ),
        sa.CheckConstraint(
            "limite_productos IS NULL OR limite_productos >= 0", name="ck_plan_limite_productos"
        ),
        sa.CheckConstraint(
            "limite_sucursales IS NULL OR limite_sucursales >= 0", name="ck_plan_limite_sucursales"
        ),
        sa.CheckConstraint(
            "limite_usuarios IS NULL OR limite_usuarios >= 0", name="ck_plan_limite_usuarios"
        ),
        sa.CheckConstraint("precio_mensual >= 0 AND precio_anual >= 0", name="ck_plan_precios"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
        sa.UniqueConstraint("nombre"),
    )
    with op.batch_alter_table("plan_saas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_saas_activo"), ["activo"], unique=False)

    op.create_table(
        "clave_api",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("prefijo", sa.String(length=16), nullable=False),
        sa.Column("secreto_hash", sa.String(length=255), nullable=False),
        sa.Column("permisos", sa.JSON(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("ultimo_uso", sa.DateTime(), nullable=True),
        sa.Column("expira_en", sa.DateTime(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "prefijo", name="uq_clave_api_prefijo"),
    )
    with op.batch_alter_table("clave_api", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clave_api_empresa_id"), ["empresa_id"], unique=False)

    op.create_table(
        "cliente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("identificacion_fiscal", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("telefono", sa.String(length=30), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "empresa_id", "identificacion_fiscal", name="uq_cliente_empresa_fiscal"
        ),
        sa.UniqueConstraint("id", "empresa_id", name="uq_cliente_id_empresa"),
    )
    with op.batch_alter_table("cliente", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cliente_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(batch_op.f("ix_cliente_empresa_id"), ["empresa_id"], unique=False)

    op.create_table(
        "configuracion_empresa",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nombre_comercial", sa.String(length=150), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("color_principal", sa.String(length=7), nullable=False),
        sa.Column("alerta_stock_bajo", sa.Boolean(), nullable=False),
        sa.Column("alerta_sobrestock", sa.Boolean(), nullable=False),
        sa.Column("dias_sin_movimiento", sa.Integer(), nullable=False),
        sa.Column("opciones", sa.JSON(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "dias_sin_movimiento BETWEEN 1 AND 3650", name="ck_configuracion_dias_sin_movimiento"
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id"),
    )
    op.create_table(
        "proveedor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("identificacion_fiscal", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("telefono", sa.String(length=30), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=True),
        sa.Column("pais", sa.String(length=2), nullable=False),
        sa.Column("sitio_web", sa.String(length=255), nullable=True),
        sa.Column("condiciones_pago", sa.String(length=120), nullable=True),
        sa.Column("dias_entrega", sa.Integer(), nullable=False),
        sa.Column("compra_minima", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.CheckConstraint("dias_entrega >= 0", name="ck_proveedor_dias_entrega"),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "empresa_id", "identificacion_fiscal", name="uq_proveedor_empresa_fiscal"
        ),
        sa.UniqueConstraint("id", "empresa_id", name="uq_proveedor_id_empresa"),
    )
    with op.batch_alter_table("proveedor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proveedor_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(batch_op.f("ix_proveedor_empresa_id"), ["empresa_id"], unique=False)

    op.create_table(
        "sucursal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=True),
        sa.Column("telefono", sa.String(length=30), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "codigo", name="uq_sucursal_empresa_codigo"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_sucursal_id_empresa"),
    )
    with op.batch_alter_table("sucursal", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sucursal_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(batch_op.f("ix_sucursal_empresa_id"), ["empresa_id"], unique=False)

    op.create_table(
        "suscripcion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("ciclo", sa.String(length=10), nullable=False),
        sa.Column("fecha_inicio", sa.DateTime(), nullable=False),
        sa.Column("fecha_fin", sa.DateTime(), nullable=True),
        sa.Column("cancelada_en", sa.DateTime(), nullable=True),
        sa.Column("motivo_cancelacion", sa.String(length=255), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("ciclo IN ('prueba','mensual','anual')", name="ck_suscripcion_ciclo"),
        sa.CheckConstraint(
            "estado IN ('prueba','activa','vencida','suspendida','cancelada')",
            name="ck_suscripcion_estado",
        ),
        sa.CheckConstraint(
            "fecha_fin IS NULL OR fecha_fin >= fecha_inicio", name="ck_suscripcion_fechas"
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan_saas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_suscripcion_id_empresa"),
    )
    with op.batch_alter_table("suscripcion", schema=None) as batch_op:
        batch_op.create_index(
            "ix_suscripcion_empresa_estado", ["empresa_id", "estado"], unique=False
        )
        batch_op.create_index(
            "uq_suscripcion_empresa_vigente",
            ["empresa_id"],
            unique=True,
            postgresql_where=sa.text("estado IN ('prueba', 'activa')"),
        )

    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("apellido", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("rol", sa.String(length=30), nullable=False),
        sa.Column("permisos_especiales", sa.JSON(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("email_verificado", sa.Boolean(), nullable=False),
        sa.Column("intentos_fallidos", sa.Integer(), nullable=False),
        sa.Column("bloqueado_hasta", sa.DateTime(), nullable=True),
        sa.Column("ultimo_acceso", sa.DateTime(), nullable=True),
        sa.Column("ultimo_cambio_password", sa.DateTime(), nullable=True),
        sa.Column("token_restablecimiento_hash", sa.String(length=64), nullable=True),
        sa.Column("token_restablecimiento_expira", sa.DateTime(), nullable=True),
        sa.Column("version_sesion", sa.Integer(), nullable=False),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=False),
        sa.Column("two_factor_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(rol = 'super_admin' AND empresa_id IS NULL) OR (rol <> 'super_admin' AND empresa_id IS NOT NULL)",
            name="ck_usuario_ambito",
        ),
        sa.CheckConstraint(
            "rol IN ('super_admin','admin_empresa','supervisor','empleado')", name="ck_usuario_rol"
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_usuario_id_empresa"),
    )
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usuario_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(batch_op.f("ix_usuario_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_usuario_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_usuario_rol"), ["rol"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_usuario_token_restablecimiento_hash"),
            ["token_restablecimiento_hash"],
            unique=True,
        )

    op.create_table(
        "auditoria",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=True),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("accion", sa.String(length=100), nullable=False),
        sa.Column("modulo", sa.String(length=50), nullable=False),
        sa.Column("entidad_tipo", sa.String(length=80), nullable=True),
        sa.Column("entidad_id", sa.BigInteger(), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("datos_anteriores", sa.JSON(), nullable=True),
        sa.Column("datos_nuevos", sa.JSON(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("agente_usuario", sa.String(length=500), nullable=True),
        sa.Column("id_solicitud", sa.String(length=100), nullable=True),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auditoria", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auditoria_accion"), ["accion"], unique=False)
        batch_op.create_index("ix_auditoria_empresa_fecha", ["empresa_id", "fecha"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditoria_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index("ix_auditoria_entidad", ["entidad_tipo", "entidad_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_auditoria_id_solicitud"), ["id_solicitud"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_auditoria_usuario_id"), ["usuario_id"], unique=False)

    op.create_table(
        "bodega",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("sucursal_id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sucursal_id", "empresa_id"],
            ["sucursal.id", "sucursal.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "codigo", name="uq_bodega_empresa_codigo"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_bodega_id_empresa"),
    )
    with op.batch_alter_table("bodega", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bodega_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(batch_op.f("ix_bodega_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bodega_sucursal_id"), ["sucursal_id"], unique=False)

    op.create_table(
        "notificacion",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("titulo", sa.String(length=150), nullable=False),
        sa.Column("mensaje", sa.Text(), nullable=False),
        sa.Column("leida", sa.Boolean(), nullable=False),
        sa.Column("leida_en", sa.DateTime(), nullable=True),
        sa.Column("referencia_tipo", sa.String(length=50), nullable=True),
        sa.Column("referencia_id", sa.BigInteger(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notificacion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notificacion_empresa_id"), ["empresa_id"], unique=False
        )
        batch_op.create_index(
            "ix_notificacion_usuario_leida", ["usuario_id", "leida"], unique=False
        )

    op.create_table(
        "producto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("proveedor_principal_id", sa.Integer(), nullable=True),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("codigo_barras", sa.String(length=150), nullable=True),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("categoria", sa.String(length=100), nullable=True),
        sa.Column("subcategoria", sa.String(length=100), nullable=True),
        sa.Column("marca", sa.String(length=100), nullable=True),
        sa.Column("unidad_medida", sa.String(length=30), nullable=False),
        sa.Column("unidades_por_caja", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("costo_referencia", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("precio_venta", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("incluye_iva", sa.Boolean(), nullable=False),
        sa.Column("tasa_impuesto", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("stock_minimo", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("punto_reorden", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("stock_maximo", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("requiere_serial", sa.Boolean(), nullable=False),
        sa.Column("controla_lotes", sa.Boolean(), nullable=False),
        sa.Column("controla_vencimiento", sa.Boolean(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "costo_referencia >= 0 AND precio_venta >= 0", name="ck_producto_precios"
        ),
        sa.CheckConstraint(
            "stock_maximo IS NULL OR stock_maximo >= stock_minimo", name="ck_producto_maximo"
        ),
        sa.CheckConstraint("stock_minimo >= 0 AND punto_reorden >= 0", name="ck_producto_minimos"),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_principal_id", "empresa_id"],
            ["proveedor.id", "proveedor.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "codigo", name="uq_producto_empresa_codigo"),
        sa.UniqueConstraint("empresa_id", "codigo_barras", name="uq_producto_empresa_barras"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_producto_id_empresa"),
    )
    with op.batch_alter_table("producto", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_producto_activo"), ["activo"], unique=False)
        batch_op.create_index(batch_op.f("ix_producto_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(batch_op.f("ix_producto_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index("ix_producto_empresa_nombre", ["empresa_id", "nombre"], unique=False)

    op.create_table(
        "solicitud_cambio_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("plan_solicitado_id", sa.Integer(), nullable=False),
        sa.Column("solicitada_por_id", sa.Integer(), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("ciclo", sa.String(length=10), nullable=False),
        sa.Column("monto_esperado", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("revisada_por_id", sa.Integer(), nullable=True),
        sa.Column("revisada_en", sa.DateTime(), nullable=True),
        sa.Column("observacion", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("ciclo IN ('mensual','anual')", name="ck_solicitud_plan_ciclo"),
        sa.CheckConstraint(
            "estado IN ('pendiente','aprobada','rechazada','cancelada')", name="ck_solicitud_estado"
        ),
        sa.CheckConstraint("monto_esperado >= 0", name="ck_solicitud_plan_monto"),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_solicitado_id"],
            ["plan_saas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solicitada_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_solicitud_plan_id_empresa"),
    )
    with op.batch_alter_table("solicitud_cambio_plan", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_solicitud_cambio_plan_empresa_id"), ["empresa_id"], unique=False
        )
        batch_op.create_index(
            "uq_solicitud_plan_pendiente",
            ["empresa_id"],
            unique=True,
            postgresql_where=sa.text("estado = 'pendiente'"),
            sqlite_where=sa.text("estado = 'pendiente'"),
        )

    op.create_table(
        "usuario_sucursal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("sucursal_id", sa.Integer(), nullable=False),
        sa.Column("es_principal", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sucursal_id", "empresa_id"],
            ["sucursal.id", "sucursal.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id", "sucursal_id", name="uq_usuario_sucursal"),
    )
    with op.batch_alter_table("usuario_sucursal", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usuario_sucursal_empresa_id"), ["empresa_id"], unique=False
        )

    op.create_table(
        "alerta_inventario",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=40), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("prioridad", sa.String(length=15), nullable=False),
        sa.Column("titulo", sa.String(length=150), nullable=False),
        sa.Column("mensaje", sa.Text(), nullable=False),
        sa.Column("datos", sa.JSON(), nullable=False),
        sa.Column("resuelta_por_id", sa.Integer(), nullable=True),
        sa.Column("resuelta_en", sa.DateTime(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("estado IN ('activa','resuelta','ignorada')", name="ck_alerta_estado"),
        sa.CheckConstraint(
            "prioridad IN ('baja','media','alta','critica')", name="ck_alerta_prioridad"
        ),
        sa.CheckConstraint(
            "tipo IN ('stock_bajo','sobrestock','riesgo_agotamiento','sin_movimiento','recomendacion_compra')",
            name="ck_alerta_tipo",
        ),
        sa.ForeignKeyConstraint(
            ["bodega_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["resuelta_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerta_inventario", schema=None) as batch_op:
        batch_op.create_index("ix_alerta_empresa_estado", ["empresa_id", "estado"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_alerta_inventario_empresa_id"), ["empresa_id"], unique=False
        )
        batch_op.create_index(
            "uq_alerta_activa",
            ["empresa_id", "producto_id", "bodega_id", "tipo"],
            unique=True,
            postgresql_where=sa.text("estado = 'activa'"),
            sqlite_where=sa.text("estado = 'activa'"),
        )

    op.create_table(
        "inventario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("cantidad_reservada", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("costo_promedio", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "cantidad >= 0 AND cantidad_reservada >= 0", name="ck_inventario_cantidades"
        ),
        sa.CheckConstraint("cantidad_reservada <= cantidad", name="ck_inventario_reserva"),
        sa.CheckConstraint("costo_promedio >= 0", name="ck_inventario_costo"),
        sa.ForeignKeyConstraint(
            ["bodega_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "empresa_id", "bodega_id", "producto_id", name="uq_inventario_producto_bodega"
        ),
        sa.UniqueConstraint("id", "empresa_id", name="uq_inventario_id_empresa"),
    )
    with op.batch_alter_table("inventario", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventario_bodega_id"), ["bodega_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventario_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventario_producto_id"), ["producto_id"], unique=False
        )

    op.create_table(
        "lote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=100), nullable=False),
        sa.Column("fecha_fabricacion", sa.Date(), nullable=True),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=True),
        sa.Column("cantidad", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("costo_unitario", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("cantidad >= 0", name="ck_lote_cantidad"),
        sa.ForeignKeyConstraint(
            ["bodega_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "empresa_id", "producto_id", "bodega_id", "numero", name="uq_lote_numero_bodega"
        ),
    )
    with op.batch_alter_table("lote", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lote_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lote_fecha_vencimiento"), ["fecha_vencimiento"], unique=False
        )

    op.create_table(
        "movimiento",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("subtipo", sa.String(length=40), nullable=True),
        sa.Column("cantidad", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("stock_anterior", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("stock_nuevo", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("costo_unitario", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("precio_unitario", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("referencia_tipo", sa.String(length=50), nullable=True),
        sa.Column("referencia_id", sa.BigInteger(), nullable=True),
        sa.Column("motivo", sa.String(length=255), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "tipo IN ('entrada','salida','ajuste','devolucion','transferencia')",
            name="ck_movimiento_tipo",
        ),
        sa.CheckConstraint("cantidad <> 0", name="ck_movimiento_cantidad"),
        sa.CheckConstraint("stock_anterior >= 0 AND stock_nuevo >= 0", name="ck_movimiento_stock"),
        sa.CheckConstraint(
            "stock_nuevo = stock_anterior + cantidad", name="ck_movimiento_ecuacion"
        ),
        sa.ForeignKeyConstraint(
            ["bodega_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movimiento", schema=None) as batch_op:
        batch_op.create_index("ix_movimiento_empresa_fecha", ["empresa_id", "fecha"], unique=False)
        batch_op.create_index(batch_op.f("ix_movimiento_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(
            "ix_movimiento_producto_fecha", ["producto_id", "fecha"], unique=False
        )

    op.create_table(
        "orden_compra",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("proveedor_id", sa.Integer(), nullable=False),
        sa.Column("bodega_destino_id", sa.Integer(), nullable=False),
        sa.Column("creada_por_id", sa.Integer(), nullable=True),
        sa.Column("numero", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("fecha_orden", sa.DateTime(), nullable=False),
        sa.Column("fecha_entrega_esperada", sa.Date(), nullable=True),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("impuesto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("cancelada_en", sa.DateTime(), nullable=True),
        sa.Column("motivo_cancelacion", sa.String(length=255), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "estado IN ('borrador','creada','enviada','parcialmente_recibida','recibida','cancelada')",
            name="ck_orden_estado",
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND descuento >= 0 AND impuesto >= 0 AND total >= 0",
            name="ck_orden_totales",
        ),
        sa.ForeignKeyConstraint(
            ["bodega_destino_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["creada_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id", "empresa_id"],
            ["proveedor.id", "proveedor.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "numero", name="uq_orden_numero"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_orden_id_empresa"),
    )
    with op.batch_alter_table("orden_compra", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orden_compra_eliminado"), ["eliminado"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_orden_compra_empresa_id"), ["empresa_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_orden_compra_estado"), ["estado"], unique=False)

    op.create_table(
        "pago",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("suscripcion_id", sa.Integer(), nullable=False),
        sa.Column("solicitud_id", sa.Integer(), nullable=False),
        sa.Column("proveedor", sa.String(length=50), nullable=False),
        sa.Column("referencia_externa", sa.String(length=150), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("monto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("metodo", sa.String(length=50), nullable=True),
        sa.Column("fecha_pago", sa.DateTime(), nullable=True),
        sa.Column("fecha_confirmacion", sa.DateTime(), nullable=True),
        sa.Column("datos_proveedor", sa.JSON(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('pendiente','procesando','pagado','rechazado','anulado','reembolsado')",
            name="ck_pago_estado",
        ),
        sa.CheckConstraint("monto >= 0", name="ck_pago_monto"),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresa.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solicitud_id", "empresa_id"],
            ["solicitud_cambio_plan.id", "solicitud_cambio_plan.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["suscripcion_id", "empresa_id"],
            ["suscripcion.id", "suscripcion.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proveedor", "referencia_externa", name="uq_pago_referencia"),
    )
    with op.batch_alter_table("pago", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pago_empresa_id"), ["empresa_id"], unique=False)

    op.create_table(
        "producto_imagen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("es_principal", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("producto_id", "orden", name="uq_imagen_orden"),
    )
    op.create_table(
        "producto_serial",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("numero_serial", sa.String(length=150), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("fecha_ingreso", sa.DateTime(), nullable=False),
        sa.Column("fecha_salida", sa.DateTime(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('ingresado','disponible','reservado','salido','devuelto','danado','perdido')",
            name="ck_serial_estado",
        ),
        sa.ForeignKeyConstraint(
            ["bodega_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "numero_serial", name="uq_serial_empresa"),
    )
    with op.batch_alter_table("producto_serial", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_producto_serial_empresa_id"), ["empresa_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_producto_serial_estado"), ["estado"], unique=False)

    op.create_table(
        "transferencia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=50), nullable=False),
        sa.Column("bodega_origen_id", sa.Integer(), nullable=False),
        sa.Column("bodega_destino_id", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("solicitada_por_id", sa.Integer(), nullable=True),
        sa.Column("despachada_por_id", sa.Integer(), nullable=True),
        sa.Column("recibida_por_id", sa.Integer(), nullable=True),
        sa.Column("fecha_solicitud", sa.DateTime(), nullable=True),
        sa.Column("fecha_despacho", sa.DateTime(), nullable=True),
        sa.Column("fecha_recepcion", sa.DateTime(), nullable=True),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('borrador','solicitada','en_transito','recibida','cancelada')",
            name="ck_transferencia_estado",
        ),
        sa.CheckConstraint(
            "bodega_origen_id <> bodega_destino_id", name="ck_transferencia_bodegas"
        ),
        sa.ForeignKeyConstraint(
            ["bodega_destino_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["bodega_origen_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["despachada_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recibida_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["solicitada_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "numero", name="uq_transferencia_numero"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_transferencia_id_empresa"),
    )
    with op.batch_alter_table("transferencia", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transferencia_empresa_id"), ["empresa_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_transferencia_estado"), ["estado"], unique=False)

    op.create_table(
        "venta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=True),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("creada_por_id", sa.Integer(), nullable=True),
        sa.Column("numero", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("impuesto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("confirmada_en", sa.DateTime(), nullable=True),
        sa.Column("cancelada_en", sa.DateTime(), nullable=True),
        sa.Column("motivo_cancelacion", sa.String(length=255), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('borrador','reservada','confirmada','cancelada')", name="ck_venta_estado"
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND descuento >= 0 AND impuesto >= 0 AND total >= 0",
            name="ck_venta_totales",
        ),
        sa.ForeignKeyConstraint(
            ["bodega_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id", "empresa_id"],
            ["cliente.id", "cliente.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["creada_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "numero", name="uq_venta_numero"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_venta_id_empresa"),
    )
    with op.batch_alter_table("venta", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_venta_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_venta_estado"), ["estado"], unique=False)

    op.create_table(
        "orden_compra_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("orden_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("cantidad_recibida", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("impuesto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "cantidad > 0 AND cantidad_recibida >= 0 AND cantidad_recibida <= cantidad",
            name="ck_orden_item_cantidades",
        ),
        sa.CheckConstraint(
            "precio_unitario >= 0 AND descuento >= 0 AND impuesto >= 0 AND total >= 0",
            name="ck_orden_item_totales",
        ),
        sa.ForeignKeyConstraint(
            ["orden_id", "empresa_id"],
            ["orden_compra.id", "orden_compra.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_orden_item_id_empresa"),
        sa.UniqueConstraint("orden_id", "producto_id", name="uq_orden_producto"),
    )
    op.create_table(
        "recepcion_compra",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("orden_id", sa.Integer(), nullable=False),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("recibida_por_id", sa.Integer(), nullable=True),
        sa.Column("numero", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("documento_referencia", sa.String(length=100), nullable=True),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('borrador','confirmada','anulada')", name="ck_recepcion_estado"
        ),
        sa.ForeignKeyConstraint(
            ["bodega_id", "empresa_id"],
            ["bodega.id", "bodega.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["orden_id", "empresa_id"],
            ["orden_compra.id", "orden_compra.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recibida_por_id", "empresa_id"],
            ["usuario.id", "usuario.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "numero", name="uq_recepcion_numero"),
        sa.UniqueConstraint("id", "empresa_id", name="uq_recepcion_id_empresa"),
    )
    op.create_table(
        "transferencia_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("transferencia_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad_solicitada", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("cantidad_despachada", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("cantidad_recibida", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "cantidad_despachada <= cantidad_solicitada", name="ck_transferencia_despacho_maximo"
        ),
        sa.CheckConstraint(
            "cantidad_recibida <= cantidad_despachada", name="ck_transferencia_recepcion_maxima"
        ),
        sa.CheckConstraint(
            "cantidad_solicitada > 0 AND cantidad_despachada >= 0 AND cantidad_recibida >= 0",
            name="ck_transferencia_cantidades",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transferencia_id", "empresa_id"],
            ["transferencia.id", "transferencia.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transferencia_id", "producto_id", name="uq_transferencia_producto"),
    )
    op.create_table(
        "venta_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("venta_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("impuesto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("cantidad > 0 AND precio_unitario >= 0", name="ck_venta_item_valores"),
        sa.CheckConstraint(
            "descuento >= 0 AND impuesto >= 0 AND total >= 0", name="ck_venta_item_totales"
        ),
        sa.ForeignKeyConstraint(
            ["producto_id", "empresa_id"],
            ["producto.id", "producto.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["venta_id", "empresa_id"],
            ["venta.id", "venta.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venta_id", "producto_id", name="uq_venta_producto"),
    )
    op.create_table(
        "recepcion_compra_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("recepcion_id", sa.Integer(), nullable=False),
        sa.Column("orden_item_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("costo_unitario", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("numero_lote", sa.String(length=100), nullable=True),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("cantidad > 0", name="ck_recepcion_item_cantidad"),
        sa.CheckConstraint("costo_unitario >= 0", name="ck_recepcion_item_costo"),
        sa.ForeignKeyConstraint(
            ["orden_item_id", "empresa_id"],
            ["orden_compra_item.id", "orden_compra_item.empresa_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recepcion_id", "empresa_id"],
            ["recepcion_compra.id", "recepcion_compra.empresa_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recepcion_id", "orden_item_id", name="uq_recepcion_orden_item"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recepcion_compra_item")
    op.drop_table("venta_item")
    op.drop_table("transferencia_item")
    op.drop_table("recepcion_compra")
    op.drop_table("orden_compra_item")
    with op.batch_alter_table("venta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_venta_estado"))
        batch_op.drop_index(batch_op.f("ix_venta_empresa_id"))

    op.drop_table("venta")
    with op.batch_alter_table("transferencia", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transferencia_estado"))
        batch_op.drop_index(batch_op.f("ix_transferencia_empresa_id"))

    op.drop_table("transferencia")
    with op.batch_alter_table("producto_serial", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_producto_serial_estado"))
        batch_op.drop_index(batch_op.f("ix_producto_serial_empresa_id"))

    op.drop_table("producto_serial")
    op.drop_table("producto_imagen")
    with op.batch_alter_table("pago", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pago_empresa_id"))

    op.drop_table("pago")
    with op.batch_alter_table("orden_compra", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orden_compra_estado"))
        batch_op.drop_index(batch_op.f("ix_orden_compra_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_orden_compra_eliminado"))

    op.drop_table("orden_compra")
    with op.batch_alter_table("movimiento", schema=None) as batch_op:
        batch_op.drop_index("ix_movimiento_producto_fecha")
        batch_op.drop_index(batch_op.f("ix_movimiento_empresa_id"))
        batch_op.drop_index("ix_movimiento_empresa_fecha")

    op.drop_table("movimiento")
    with op.batch_alter_table("lote", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lote_fecha_vencimiento"))
        batch_op.drop_index(batch_op.f("ix_lote_empresa_id"))

    op.drop_table("lote")
    with op.batch_alter_table("inventario", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventario_producto_id"))
        batch_op.drop_index(batch_op.f("ix_inventario_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_inventario_bodega_id"))

    op.drop_table("inventario")
    with op.batch_alter_table("alerta_inventario", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_alerta_activa",
            postgresql_where=sa.text("estado = 'activa'"),
            sqlite_where=sa.text("estado = 'activa'"),
        )
        batch_op.drop_index(batch_op.f("ix_alerta_inventario_empresa_id"))
        batch_op.drop_index("ix_alerta_empresa_estado")

    op.drop_table("alerta_inventario")
    with op.batch_alter_table("usuario_sucursal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuario_sucursal_empresa_id"))

    op.drop_table("usuario_sucursal")
    with op.batch_alter_table("solicitud_cambio_plan", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_solicitud_plan_pendiente",
            postgresql_where=sa.text("estado = 'pendiente'"),
            sqlite_where=sa.text("estado = 'pendiente'"),
        )
        batch_op.drop_index(batch_op.f("ix_solicitud_cambio_plan_empresa_id"))

    op.drop_table("solicitud_cambio_plan")
    with op.batch_alter_table("producto", schema=None) as batch_op:
        batch_op.drop_index("ix_producto_empresa_nombre")
        batch_op.drop_index(batch_op.f("ix_producto_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_producto_eliminado"))
        batch_op.drop_index(batch_op.f("ix_producto_activo"))

    op.drop_table("producto")
    with op.batch_alter_table("notificacion", schema=None) as batch_op:
        batch_op.drop_index("ix_notificacion_usuario_leida")
        batch_op.drop_index(batch_op.f("ix_notificacion_empresa_id"))

    op.drop_table("notificacion")
    with op.batch_alter_table("bodega", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bodega_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_bodega_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_bodega_eliminado"))

    op.drop_table("bodega")
    with op.batch_alter_table("auditoria", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auditoria_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_auditoria_id_solicitud"))
        batch_op.drop_index("ix_auditoria_entidad")
        batch_op.drop_index(batch_op.f("ix_auditoria_empresa_id"))
        batch_op.drop_index("ix_auditoria_empresa_fecha")
        batch_op.drop_index(batch_op.f("ix_auditoria_accion"))

    op.drop_table("auditoria")
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuario_token_restablecimiento_hash"))
        batch_op.drop_index(batch_op.f("ix_usuario_rol"))
        batch_op.drop_index(batch_op.f("ix_usuario_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_usuario_email"))
        batch_op.drop_index(batch_op.f("ix_usuario_eliminado"))

    op.drop_table("usuario")
    with op.batch_alter_table("suscripcion", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_suscripcion_empresa_vigente",
            postgresql_where=sa.text("estado IN ('prueba', 'activa')"),
        )
        batch_op.drop_index("ix_suscripcion_empresa_estado")

    op.drop_table("suscripcion")
    with op.batch_alter_table("sucursal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sucursal_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_sucursal_eliminado"))

    op.drop_table("sucursal")
    with op.batch_alter_table("proveedor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proveedor_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_proveedor_eliminado"))

    op.drop_table("proveedor")
    op.drop_table("configuracion_empresa")
    with op.batch_alter_table("cliente", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cliente_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_cliente_eliminado"))

    op.drop_table("cliente")
    with op.batch_alter_table("clave_api", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clave_api_empresa_id"))

    op.drop_table("clave_api")
    with op.batch_alter_table("plan_saas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_saas_activo"))

    op.drop_table("plan_saas")
    with op.batch_alter_table("limite_solicitud", schema=None) as batch_op:
        batch_op.drop_index("ix_limite_solicitud_expira")

    op.drop_table("limite_solicitud")
    with op.batch_alter_table("empresa", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_empresa_estado"))
        batch_op.drop_index(batch_op.f("ix_empresa_eliminado"))

    op.drop_table("empresa")
    # ### end Alembic commands ###
