"""agrega suite comercial prioritaria

Revision ID: c4c508486ee1
Revises: f9a2c4d6e8b0
Create Date: 2026-08-22 18:00:36.900978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c508486ee1'
down_revision = 'f9a2c4d6e8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('moneda_consolidacion', sa.String(length=3), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('integracion_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('configuracion', sa.JSON(), nullable=False),
    sa.Column('secreto_webhook_hash', sa.String(length=64), nullable=True),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.Column('sincronizada_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('activa','pausada','error')", name='ck_integracion_estado'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'proveedor', name='uq_integracion_empresa_proveedor')
    )
    with op.batch_alter_table('integracion_empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integracion_empresa_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('membresia_grupo_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rol IN ('propietaria','filial')", name='ck_membresia_grupo_rol'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id'),
    sa.UniqueConstraint('grupo_id', 'empresa_id', name='uq_grupo_empresa')
    )
    op.create_table('acceso_empresa_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rol IN ('jefe','supervisor','empleado','consulta')", name='ck_acceso_rol'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'empresa_id', name='uq_acceso_usuario_empresa')
    )
    op.create_table('caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id', 'empresa_id'], ['sucursal.id', 'sucursal.empresa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_caja_empresa_codigo'),
    sa.UniqueConstraint('id', 'empresa_id', name='uq_caja_id_empresa')
    )
    with op.batch_alter_table('caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caja_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('evento_integracion',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('integracion_id', sa.Integer(), nullable=False),
    sa.Column('evento_externo_id', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('procesado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('recibido','procesado','error')", name='ck_evento_integracion_estado'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['integracion_id'], ['integracion_empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integracion_id', 'evento_externo_id', name='uq_evento_integracion_externo')
    )
    with op.batch_alter_table('evento_integracion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_integracion_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('turno_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('usuario_apertura_id', sa.Integer(), nullable=False),
    sa.Column('usuario_cierre_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('monto_apertura', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_cierre_declarado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monto_cierre_calculado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('abierto_en', sa.DateTime(), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('abierto','cerrado')", name='ck_turno_caja_estado'),
    sa.CheckConstraint('monto_apertura >= 0', name='ck_turno_apertura'),
    sa.ForeignKeyConstraint(['caja_id', 'empresa_id'], ['caja.id', 'caja.empresa_id'], ),
    sa.ForeignKeyConstraint(['usuario_apertura_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_cierre_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'empresa_id', name='uq_turno_caja_id_empresa')
    )
    with op.batch_alter_table('turno_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turno_caja_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index('uq_turno_caja_abierto', ['caja_id'], unique=True, postgresql_where=sa.text("estado = 'abierto'"), sqlite_where=sa.text("estado = 'abierto'"))

    op.create_table('documento_tributario',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('folio', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('proveedor', sa.String(length=50), nullable=False),
    sa.Column('referencia_proveedor', sa.String(length=150), nullable=True),
    sa.Column('clave_idempotencia', sa.String(length=100), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('datos_proveedor', sa.JSON(), nullable=False),
    sa.Column('emitido_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('borrador','enviando','aceptado','rechazado','anulado','incidencia')", name='ck_dte_estado'),
    sa.CheckConstraint("tipo IN ('boleta','factura','factura_exenta','nota_credito','nota_debito','guia_despacho')", name='ck_dte_tipo'),
    sa.ForeignKeyConstraint(['venta_id', 'empresa_id'], ['venta.id', 'venta.empresa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'clave_idempotencia', name='uq_dte_idempotencia'),
    sa.UniqueConstraint('empresa_id', 'tipo', 'folio', name='uq_dte_empresa_tipo_folio')
    )
    with op.batch_alter_table('documento_tributario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_tributario_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('orden_wms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('asignada_a_id', sa.Integer(), nullable=True),
    sa.Column('transportista', sa.String(length=100), nullable=True),
    sa.Column('seguimiento', sa.String(length=150), nullable=True),
    sa.Column('pickeada_en', sa.DateTime(), nullable=True),
    sa.Column('empacada_en', sa.DateTime(), nullable=True),
    sa.Column('despachada_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente','picking','pickeada','packing','empacada','despachada','cancelada')", name='ck_orden_wms_estado'),
    sa.ForeignKeyConstraint(['asignada_a_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['bodega_id', 'empresa_id'], ['bodega.id', 'bodega.empresa_id'], ),
    sa.ForeignKeyConstraint(['venta_id', 'empresa_id'], ['venta.id', 'venta.empresa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero', name='uq_orden_wms_numero'),
    sa.UniqueConstraint('venta_id', name='uq_orden_wms_venta')
    )
    with op.batch_alter_table('orden_wms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orden_wms_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('pago_venta',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=150), nullable=True),
    sa.Column('clave_idempotencia', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.CheckConstraint("metodo IN ('efectivo','debito','credito','transferencia','qr','otro')", name='ck_pago_venta_metodo'),
    sa.CheckConstraint('monto > 0', name='ck_pago_venta_monto'),
    sa.ForeignKeyConstraint(['turno_id', 'empresa_id'], ['turno_caja.id', 'turno_caja.empresa_id'], ),
    sa.ForeignKeyConstraint(['venta_id', 'empresa_id'], ['venta.id', 'venta.empresa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'clave_idempotencia', name='uq_pago_venta_idempotencia')
    )
    with op.batch_alter_table('pago_venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pago_venta_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago_venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pago_venta_empresa_id'))

    op.drop_table('pago_venta')
    with op.batch_alter_table('orden_wms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orden_wms_empresa_id'))

    op.drop_table('orden_wms')
    with op.batch_alter_table('documento_tributario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_tributario_empresa_id'))

    op.drop_table('documento_tributario')
    with op.batch_alter_table('turno_caja', schema=None) as batch_op:
        batch_op.drop_index('uq_turno_caja_abierto', postgresql_where=sa.text("estado = 'abierto'"), sqlite_where=sa.text("estado = 'abierto'"))
        batch_op.drop_index(batch_op.f('ix_turno_caja_empresa_id'))

    op.drop_table('turno_caja')
    with op.batch_alter_table('evento_integracion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_integracion_empresa_id'))

    op.drop_table('evento_integracion')
    with op.batch_alter_table('caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caja_empresa_id'))

    op.drop_table('caja')
    op.drop_table('acceso_empresa_usuario')
    op.drop_table('membresia_grupo_empresa')
    with op.batch_alter_table('integracion_empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integracion_empresa_empresa_id'))

    op.drop_table('integracion_empresa')
    op.drop_table('grupo_empresa')
    # ### end Alembic commands ###
